name: Docker Image CI
permissions:
  packages: write
  contents: read
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Extract branch name
      shell: bash
      run: echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
      
    - name: Build and tag Docker image
      run: |
        # Create timestamp tag
        TIMESTAMP=$(date +%s)
        echo "TIMESTAMP=$TIMESTAMP" >> $GITHUB_ENV
        
        # Extract repo owner and image name
        REPO_OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
        IMAGE_NAME=$(echo "${{ github.event.repository.name }}" | tr '[:upper:]' '[:lower:]')
        
        # Create branch-specific tag
        BRANCH_TAG="${{ env.BRANCH_NAME }}"
        echo "BRANCH_TAG=$BRANCH_TAG" >> $GITHUB_ENV
        
        # Create combined tag (branch-timestamp)
        COMBINED_TAG="${{ env.BRANCH_NAME }}-$TIMESTAMP"
        echo "COMBINED_TAG=$COMBINED_TAG" >> $GITHUB_ENV
        
        # Build image with multiple tags
        docker build . --file Dockerfile \
          --tag ghcr.io/$REPO_OWNER/$IMAGE_NAME:$COMBINED_TAG \
          --tag ghcr.io/$REPO_OWNER/$IMAGE_NAME:$BRANCH_TAG \
          --tag ghcr.io/$REPO_OWNER/$IMAGE_NAME:latest
        
    - name: Push to GitHub Container Registry
      run: |
        REPO_OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
        IMAGE_NAME=$(echo "${{ github.event.repository.name }}" | tr '[:upper:]' '[:lower:]')
        
        # Push all tags
        docker push ghcr.io/$REPO_OWNER/$IMAGE_NAME:${{ env.COMBINED_TAG }}
        docker push ghcr.io/$REPO_OWNER/$IMAGE_NAME:${{ env.BRANCH_TAG }}
        docker push ghcr.io/$REPO_OWNER/$IMAGE_NAME:latest
